### ISSUE TITLE
Rust language things

### ISSUE THREAD

**Issue by rajasekharponakala** [AllAlgorithms/cpp#103]
This project is awesome!. Looking more on Rust based problems too!

**Comment by abranhe** [comment]
Thanks for being interested on [The All ▲lgorithms][1] project, the huge collection of algorithms implemented in different languages. You can give us a start 😃!

If you are looking for Rust you can submit your algorithm at [AllAlgorithms/Rust][2]

[1]: https://github.com/AllAlgorithms
[2]: https://github.com/AllAlgorithms/Rust
