### ISSUE TITLE
Know any algorithm in C++?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/cpp#6]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [C Plus Plus](https://github.com/AllAlgorithms/cpp) this case

**Comment by roopbiswas** [comment]
I would like to contribute. Can you please elaborate on this issue?

**Comment by abranhe** [comment]
Yes, if you want to implement any algorithm you can do so by storing it in a relevant folder, probably is already created, but it if isn't you can feel free to create it. Be sure to include the path for the new folder on the `README.md` file

**Comment by Ishaan28malik** [comment]
@abranhe I have created one for Dijkastra's algorithm pls chk

**Comment by anupamdas104** [comment]
@abranhe Pull request sent for Fibonacci function.
