### ISSUE TITLE
Do you know any algorithm in C++?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/cpp#97]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [C Plus Plus](https://github.com/AllAlgorithms/cpp) this case

**Comment by codegirl20** [comment]
Hi @abranhe , Yes I do know some, kindly elaborate how can I help?

**Comment by codegirl20** [comment]
I am working to add the subset sum problem in the dp .cpp section.

**Comment by korostenskyi** [comment]
I've added no-recursive factorial algorithm.

**Comment by ananthuc73** [comment]
Quick sort algorithm

**Comment by ananthuc73** [comment]
Added BucketSorting program

**Comment by AkkiBond** [comment]
I want to add fibonacci number algorithm with o(logn) complexity.

**Comment by TheBestTvarynka** [comment]
Added stacks (array and list based) that writed with classes in c++
pr #233

**Comment by TheBestTvarynka** [comment]
> Added stacks (array and list based) that writed with classes in c++
> pr #233

#233

**Comment by Ankitr19** [comment]
Added naive disjoint set union https://github.com/AllAlgorithms/cpp/pull/246
